### ISSUE TITLE
vsearch instead of usearch

### ISSUE THREAD

**Issue by ereyred** [aleixop/Malaspina_Euk_mTags#1]
Hello! I would love to use this pipeline to identify eukaryotic OTUs but I'm having trouble using my own data.

First of all, when I tried to run with usearch it said that my files were too big and that I needed to use the 64-bit version which is not free. So I am using vsearch instead of usearch, which seems to work.

In 1-mtags_classification.sh, can you first of all tell me what to input into these?
FASTA=X #is this the .fna output of the 0-mtags_extraction.sh step?
MAP=X #is this the .blast (or .hits) output of 0-mtags_extraction.sh?
DB=X #the eukv4 db fasta? Or the eukv4_tax.txt version of the db? The latter gave me an error.

Running 1-mtags_classification.sh with eukv4_db.fasta gives me an OTU table but the output is not very intelligible:
AB353771_Dinoflagellata_Alveolata
AB551723_Metazoa_Opisthokonta
MPN923_Labyrinthulomycetes_Stramenopiles

I have phylum and class, but what are these numbers and letters and how do I make sense of it?
I'm quite new to this so need everything explained a bit more. Thank you for your help!

**Comment by aleixop** [comment]
Hi @ereyred, thanks for your interest! When I wrote these scripts some years ago I used `USEARCH` because it was able to perform local alignments instead of global. In any case, now I think it is not necessary and that `VSEARCH` with global alignment should be used (given it's open-source and freely accessible) and results would be the same (or very similar).

So, about your questions, I guess you were able to extract the mTags with the [0-mtags_extraction.sh](https://github.com/aleixop/Malaspina_Euk_mTags/blob/master/scripts/mtags_pipeline/0-mtags_extraction.sh) script, right? And now you have a fasta with them. Revisiting now the scripts, I see that variable names are not very self-explanatory and can be misleading. Here I will try to explain them:

- `FASTA`: the fasta file with the extracted mTags you obtained in the previous script.
- `DB`: path to eukaryotesV4 database in fasta format. I recommend you use the latest release, now [v8](https://github.com/aleixop/eukaryotesV4/blob/master/db/eukaryotesV4_v8.fasta).
- `MAP`: a name that will be used for the output UC file that `VSEARCH` writes. It can be anything, for example `output.uc`.
- `OUT_TABLE`: an output directory where the final OTU table will be written.
- `OUT_MAP`: an output directory where the UC file (the one specified in variable `MAP`) will be written.
- `OUT_NAME`: the name of the final file (it will be used to name the OTU table).

Regarding the output, you will have 3 taxonomic levels separated by `_`, just as the examples you show. The first field is the most specific one, the OTU level (basically is the id of an specific sequence in the database). If you check these ids in the [taxonomy file of eukaryotesV4](https://github.com/aleixop/eukaryotesV4/blob/master/db/eukaryotesV4_tax_v8.txt), you will be able to extract more information (PR2 taxonomy, closest cultured species, etc.). The second level is Group (something similar to Class), and the third one is supergroup. Given that metagenomic Illumina tags are very short, the phylogenetic information they contain is limited. Thus, there will be cases where the same mTag will have an exact best match with more than one reference in the database. This is where the script [mtags_consensus_tax_v2.py](https://github.com/aleixop/Malaspina_Euk_mTags/blob/master/scripts/mtags_pipeline/mtags_consensus_tax_v2.py) comes into play. So, in cases with multiple hits to references that belong to the same group, the OTU level will be dropped (you will see `NA` instead, e.g., NA_MAST-4_Stramenopiles). Then, if an mTAG has multiple hits to different groups but same supergroup, both OTU and Group levels will be dropped (e.g., NA_NA_Stramenopiles). And finally, if the multiple hits belong to different supergroups, the read will be completely ambiguous (NA_NA_NA). In general, using Illumina mTags to assess the taxonomy of a community will give you a very good resolution at the Group level, but not at the OTU one, as we argue in [our paper](https://doi.org/10.1111/1755-0998.13147).

I hope I solved your questions, let me know if you are able to finish the analyses. If not, I can help you with it! 

Aleix

**Comment by ereyred** [comment]
Hi Aleix,
Thanks so much!

Ok so it's working for me but only when I run each sample individually (in separate DATA_DIRs). Is there a way to run this pipeline to output an OTU table for all my samples combined, eg:
OTUId                                                                         Sample 1                Sample 2
AB353771_Dinoflagellata_Alveolata                               500                           0
AB551723_Metazoa_Opisthokonta                                180                          37
MPN923_Labyrinthulomycetes_Stramenopiles                0                             3

Otherwise I cannot combine the outputs into one table myself because they don't all contain the same OTUs.

All this considering that I have paired end fastq reads to begin with. ie can I run:
Sample1_1.fastq
Sample1_2.fastq
Sample2_1.fastq
Sample2_2.fastq
To output the OTU table above?

I don't know what this SLURM_ARRAY_TASK_ID thing is or how to select the Sample ID with paired end reads. When I run steps 0.sh and 1.sh on a directory containing my two samples my output OTU table is only for one sample (one abundance column).

And another thing, is there a way to output the taxonomic (CCM) names in eukaryotesV4_tax_v8.txt in the OTU table instead of the OTU codes? Thanks sososo much,
E

**Comment by aleixop** [comment]
Hi again!

The idea is to run script 0 for all your samples to get a separate fasta file per sample with the mTags it contains. The script is written to work with a supercomputer with SLURM and an array of jobs (that's why this SLURM_ARRAY_TASK_ID is there). You could also write a loop to iterate your samples. 

Then, you need to concatenate all the obtained fasta files into one single file (with `cat`, for example). And this is the file you give script 1 as input.

About adding the CCM information, there are several ways to do it, but you could use `R` and the function `left_join` from `dplyr` package.

Aleix

**Comment by aleixop** [comment]
Hi again!

The idea is to run script 0 for all your samples to get a separate fasta file per sample with the mTags it contains. The script is written to work with a supercomputer with SLURM and an array of jobs (that's why this SLURM_ARRAY_TASK_ID is there). You could also write a loop to iterate your samples. 

Then, you need to concatenate all the obtained fasta files into one single file (with `cat`, for example). And this is the file you give script 1 as input.

About adding the CCM information, there are several ways to do it, but you could use `R` and the function `left_join` from `dplyr` package.

Aleix

**Comment by ereyred** [comment]
Hi Aleix,
Sorry to bother again..

#Then, you need to concatenate all the obtained fasta files into one single file (with cat, for example). And this is the file you give script 1 as input.
If I do this I won't obtain a table with the abundance for all my samples (several abundance columns), I'll just get a combined abundance for all samples. Is there a way to output one by one all my sample abundances, but in a way that outputs all the taxonomies, even the ones that have zero counts, so that I can combine them myself?
You know what I mean? 
Separately I have:

(A)
OTUId_____sample1
tax1__________2
tax3__________2
tax5_________15

and

(B)
OTUId_____sample2
tax1__________1
tax2__________4
tax4__________1

but what I want is

(C)
OTUId_____sample1_____sample2
tax1__________2_____________1
tax2__________0_____________4
tax3__________2_____________0
tax4__________0_____________1
tax5_________15_____________0

For example, sample1 (A) has tax1, tax3 and tax5 present, whereas sample2 (B) has tax1, tax2, tax4. Combining the separate abundance matrices (A+B) of these two samples is difficult because they have different rows. Is there a way to output (C) this way, with the zeros for absent taxonomies, or output all samples at once in different columns without adding up the counts? 
A million thanks again,
Elvira

**Comment by aleixop** [comment]
Maybe sample names are not being appended correctly to the separate fasta files and that is why you get everything merged. Or other things could happen depending on how are your files. I would need to see your script and files to check what is happening exactly.

In any case, if you already have separate OTU tables, you can merge them with `R` using the `dplyr`'s function `full_join()`. This will give you the full the table you want.

Aleix

**Comment by ereyred** [comment]
I figured it out! 
Here are my fixes which are not very elegant (I'm a bit of a noob in all this) but it works, in case anyone else has the same issues/wants to do the same as me.

**Issue #1, the taxonomic names in the abundance matrix**
I made a taxonomy table with just the OTUIds and corresponding genus/species names.
[eukaryotesV4_taxnames.txt](https://github.com/aleixop/Malaspina_Euk_mTags/files/14943161/eukaryotesV4_taxnames.txt)
You can use this and this code to replace the OTUIds with the genus/sp name, eg
"MPN281_Metazoa_Opisthokonta" becomes "Hydroides-elegans_Metazoa_Opisthokonta" (I made the genus_sp underscores here dashes to prevent tax level confusion down the line). 
The code is:

declare -A tax_dict
while IFS=$'\t' read -r col1 col2 col3; do
    tax_dict["$col1"]="$col2"
done < eukaryotesV4_taxnames.txt

while IFS=$'\t' read -r col1 col2; do
    A=$(echo "$col1" | cut -d'_' -f1)
    if [[ -n "${tax_dict[$A]}" ]]; then
        new_col1="${tax_dict[$A]}_${col1#*_}"
        new_col1="${new_col1%$'\n'}"
        echo -e "${new_col1//$'\n'}\t${col2//$'\n'}" >> editedtaxotuTable.txt
    else
        echo -e "${col1//$'\n'}\t${col2//$'\n'}" >> editedtaxotuTable.txt
    fi
done < otuTable.txt
________________________________________________________________________

**Issue #2, the abundance matrix for one sample doesn't have all the taxonomies present in another sample which makes it hard to merge**
I made a list of all the OTUIds possible (including NA_Group_Subgroup ones), so after editing the taxnames you can add these to the end of your abundance matrix on Excel and remove duplicates so you're left with all your taxonomies present plus all your taxonomies with zero abundance, and once ordered alphabetically you can merge all your samples into one abundance table!
[eukaryotesV4_alltax.txt](https://github.com/aleixop/Malaspina_Euk_mTags/files/14943288/eukaryotesV4_alltax.txt)

Thanks so much Aleix, hopefully I'll leave you alone now :)
All the best,
Elvira
